// Dados do sorteio - SUBSTITUIR COM OS RESULTADOS REAIS DO TEU SORTEIO
const sorteioFinal = {
    'Miguel': 'Vanessa',
    'Maria': 'Tia Ze', 
    'Ricardo': 'Isabel F',
    'Fernando': 'Rita',
    'Gloria': 'To',
    'Marcelo': 'Gloria',
    'Rita': 'Beta',
    'Tia Ze': 'Francisco',
    'Mafalda': 'Ricardo',
    'Zé': 'Marlene',
    'Isabel Silva': 'Avó Candida',
    'Diogo': 'Zé',
    'Vanessa': 'Filipa',
    'Sofia': 'Rui',
    'To': 'Maria',
    'Lucia': 'Tia Rosa',
    'Filipa': 'Diogo',
    'Francisco': 'Sofia',
    'Isabel F': 'Tia Dete',
    'Beta': 'Isabel Silva',
    'Rui': 'Roberto',
    'Tia Rosa': 'Miguel',
    'Tia Dete': 'Mafalda',
    'Marlene': 'Lucia',
    'Roberto': 'Fernando',
    'Avó Candida': 'Marcelo'
};

// Códigos pessoais para cada participante
const codigosPessoais = {
    'Miguel': 'N28471',
    'Maria': 'N39285',
    'Ricardo': 'N15632',
    'Fernando': 'N47896',
    'Gloria': 'N56321',
    'Marcelo': 'N68947',
    'Rita': 'N74258',
    'Tia Ze': 'N81563',
    'Mafalda': 'N92634',
    'Zé': 'N13475',
    'Isabel Silva': 'N25789',
    'Diogo': 'N36842',
    'Vanessa': 'N49267',
    'Sofia': 'N51839',
    'To': 'N67412',
    'Lucia': 'N78523',
    'Filipa': 'N83156',
    'Francisco': 'N94627',
    'Isabel F': 'N12384',
    'Beta': 'N23495',
    'Rui': 'N34516',
    'Tia Rosa': 'N45627',
    'Tia Dete': 'N56738',
    'Marlene': 'N67849',
    'Roberto': 'N78951',
    'Avó Candida': 'N89162'
};