const sorteioFinal = {
    'Miguel': 'Rita',
    'Maria': 'Zé Carlos',
    'Ricardo': 'Marlene',
    'Fernando': 'Isabel Silva',
    'Gloria': 'Mafalda',
    'Marcelo': 'Rui',
    'Rita': 'Gloria',
    'Maria José': 'Fernando',
    'Mafalda': 'Vanessa',
    'Zé Carlos': 'Lucia Paula',
    'Isabel Silva': 'Diogo',
    'Diogo': 'Filipa',
    'Vanessa': 'Tia Dete',
    'Sofia': 'Avó Candida',
    'Tó': 'Maria',
    'Lucia Paula': 'Roberto',
    'Filipa': 'Isabel Freitas',
    'Francisco': 'Marcelo',
    'Isabel Freitas': 'Tó',
    'Beta': 'Ricardo',
    'Rui': 'Maria José',
    'Tia Rosa': 'Francisco',
    'Tia Dete': 'Miguel',
    'Marlene': 'Tia Rosa',
    'Roberto': 'Sofia',
    'Avó Candida': 'Beta',
};

const codigosPessoais = {
    'Teste': 'N12345',
    'Miguel': 'N28471',
    'Maria': 'N39285',
    'Ricardo': 'N15632',
    'Fernando': 'N47896',
    'Gloria': 'N56321',
    'Marcelo': 'N68947',
    'Rita': 'N74258',
    'Tia Ze': 'N81563',
    'Mafalda': 'N92634',
    'Zé': 'N13475',
    'Isabel Silva': 'N25789',
    'Diogo': 'N36842',
    'Vanessa': 'N49267',
    'Sofia': 'N51839',
    'To': 'N67412',
    'Lucia': 'N78523',
    'Filipa': 'N83156',
    'Francisco': 'N94627',
    'Isabel F': 'N12384',
    'Beta': 'N23495',
    'Rui': 'N34516',
    'Tia Rosa': 'N45627',
    'Tia Dete': 'N56738',
    'Marlene': 'N67849',
    'Roberto': 'N78951',
    'Avó Candida': 'N89162'
};
